export const GET_VIDEOS_BY_QUERY_REQUEST = 'GET_VIDEOS_BY_QUERY_REQUEST';
export const GET_VIDEOS_BY_QUERY_SUCCESS = 'GET_VIDEOS_BY_QUERY_SUCCESS';
export const GET_VIDEOS_BY_QUERY_FAILURE = 'GET_VIDEOS_BY_QUERY_FAILURE';

export const GET_FAVOURITE_VIDEOS_REQUEST = 'GET_FAVOURITE_VIDEOS_REQUEST';
export const GET_FAVOURITE_VIDEOS_SUCCESS = 'GET_FAVOURITE_VIDEOS_SUCCESS';
export const GET_FAVOURITE_VIDEOS_FAILURE = 'GET_FAVOURITE_VIDEOS_FAILURE';

export const SET_ONLY_FAVOURITE_MODE = 'SET_ONLY_FAVOURITE_MODE';

export const CLEAR_VIDEOS = 'CLEAR_VIDEOS';

